var searchData=
[
  ['background_2470',['background',['../classtd_1_1td__api_1_1background.html',1,'td::td_api']]],
  ['backgroundfill_2471',['BackgroundFill',['../classtd_1_1td__api_1_1_background_fill.html',1,'td::td_api']]],
  ['backgroundfillgradient_2472',['backgroundFillGradient',['../classtd_1_1td__api_1_1background_fill_gradient.html',1,'td::td_api']]],
  ['backgroundfillsolid_2473',['backgroundFillSolid',['../classtd_1_1td__api_1_1background_fill_solid.html',1,'td::td_api']]],
  ['backgrounds_2474',['backgrounds',['../classtd_1_1td__api_1_1backgrounds.html',1,'td::td_api']]],
  ['backgroundtype_2475',['BackgroundType',['../classtd_1_1td__api_1_1_background_type.html',1,'td::td_api']]],
  ['backgroundtypefill_2476',['backgroundTypeFill',['../classtd_1_1td__api_1_1background_type_fill.html',1,'td::td_api']]],
  ['backgroundtypepattern_2477',['backgroundTypePattern',['../classtd_1_1td__api_1_1background_type_pattern.html',1,'td::td_api']]],
  ['backgroundtypewallpaper_2478',['backgroundTypeWallpaper',['../classtd_1_1td__api_1_1background_type_wallpaper.html',1,'td::td_api']]],
  ['banchatmember_2479',['banChatMember',['../classtd_1_1td__api_1_1ban_chat_member.html',1,'td::td_api']]],
  ['bankcardactionopenurl_2480',['bankCardActionOpenUrl',['../classtd_1_1td__api_1_1bank_card_action_open_url.html',1,'td::td_api']]],
  ['bankcardinfo_2481',['bankCardInfo',['../classtd_1_1td__api_1_1bank_card_info.html',1,'td::td_api']]],
  ['basicgroup_2482',['basicGroup',['../classtd_1_1td__api_1_1basic_group.html',1,'td::td_api']]],
  ['basicgroupfullinfo_2483',['basicGroupFullInfo',['../classtd_1_1td__api_1_1basic_group_full_info.html',1,'td::td_api']]],
  ['blockmessagesenderfromreplies_2484',['blockMessageSenderFromReplies',['../classtd_1_1td__api_1_1block_message_sender_from_replies.html',1,'td::td_api']]],
  ['botcommand_2485',['botCommand',['../classtd_1_1td__api_1_1bot_command.html',1,'td::td_api']]],
  ['botinfo_2486',['botInfo',['../classtd_1_1td__api_1_1bot_info.html',1,'td::td_api']]]
];
