var searchData=
[
  ['background_2432',['background',['../classtd_1_1td__api_1_1background.html',1,'td::td_api']]],
  ['backgroundfill_2433',['BackgroundFill',['../classtd_1_1td__api_1_1_background_fill.html',1,'td::td_api']]],
  ['backgroundfillgradient_2434',['backgroundFillGradient',['../classtd_1_1td__api_1_1background_fill_gradient.html',1,'td::td_api']]],
  ['backgroundfillsolid_2435',['backgroundFillSolid',['../classtd_1_1td__api_1_1background_fill_solid.html',1,'td::td_api']]],
  ['backgrounds_2436',['backgrounds',['../classtd_1_1td__api_1_1backgrounds.html',1,'td::td_api']]],
  ['backgroundtype_2437',['BackgroundType',['../classtd_1_1td__api_1_1_background_type.html',1,'td::td_api']]],
  ['backgroundtypefill_2438',['backgroundTypeFill',['../classtd_1_1td__api_1_1background_type_fill.html',1,'td::td_api']]],
  ['backgroundtypepattern_2439',['backgroundTypePattern',['../classtd_1_1td__api_1_1background_type_pattern.html',1,'td::td_api']]],
  ['backgroundtypewallpaper_2440',['backgroundTypeWallpaper',['../classtd_1_1td__api_1_1background_type_wallpaper.html',1,'td::td_api']]],
  ['bankcardactionopenurl_2441',['bankCardActionOpenUrl',['../classtd_1_1td__api_1_1bank_card_action_open_url.html',1,'td::td_api']]],
  ['bankcardinfo_2442',['bankCardInfo',['../classtd_1_1td__api_1_1bank_card_info.html',1,'td::td_api']]],
  ['basicgroup_2443',['basicGroup',['../classtd_1_1td__api_1_1basic_group.html',1,'td::td_api']]],
  ['basicgroupfullinfo_2444',['basicGroupFullInfo',['../classtd_1_1td__api_1_1basic_group_full_info.html',1,'td::td_api']]],
  ['blockmessagesenderfromreplies_2445',['blockMessageSenderFromReplies',['../classtd_1_1td__api_1_1block_message_sender_from_replies.html',1,'td::td_api']]],
  ['botcommand_2446',['botCommand',['../classtd_1_1td__api_1_1bot_command.html',1,'td::td_api']]],
  ['botinfo_2447',['botInfo',['../classtd_1_1td__api_1_1bot_info.html',1,'td::td_api']]]
];
