var searchData=
[
  ['background_2468',['background',['../classtd_1_1td__api_1_1background.html',1,'td::td_api']]],
  ['backgroundfill_2469',['BackgroundFill',['../classtd_1_1td__api_1_1_background_fill.html',1,'td::td_api']]],
  ['backgroundfillgradient_2470',['backgroundFillGradient',['../classtd_1_1td__api_1_1background_fill_gradient.html',1,'td::td_api']]],
  ['backgroundfillsolid_2471',['backgroundFillSolid',['../classtd_1_1td__api_1_1background_fill_solid.html',1,'td::td_api']]],
  ['backgrounds_2472',['backgrounds',['../classtd_1_1td__api_1_1backgrounds.html',1,'td::td_api']]],
  ['backgroundtype_2473',['BackgroundType',['../classtd_1_1td__api_1_1_background_type.html',1,'td::td_api']]],
  ['backgroundtypefill_2474',['backgroundTypeFill',['../classtd_1_1td__api_1_1background_type_fill.html',1,'td::td_api']]],
  ['backgroundtypepattern_2475',['backgroundTypePattern',['../classtd_1_1td__api_1_1background_type_pattern.html',1,'td::td_api']]],
  ['backgroundtypewallpaper_2476',['backgroundTypeWallpaper',['../classtd_1_1td__api_1_1background_type_wallpaper.html',1,'td::td_api']]],
  ['banchatmember_2477',['banChatMember',['../classtd_1_1td__api_1_1ban_chat_member.html',1,'td::td_api']]],
  ['bankcardactionopenurl_2478',['bankCardActionOpenUrl',['../classtd_1_1td__api_1_1bank_card_action_open_url.html',1,'td::td_api']]],
  ['bankcardinfo_2479',['bankCardInfo',['../classtd_1_1td__api_1_1bank_card_info.html',1,'td::td_api']]],
  ['basicgroup_2480',['basicGroup',['../classtd_1_1td__api_1_1basic_group.html',1,'td::td_api']]],
  ['basicgroupfullinfo_2481',['basicGroupFullInfo',['../classtd_1_1td__api_1_1basic_group_full_info.html',1,'td::td_api']]],
  ['blockmessagesenderfromreplies_2482',['blockMessageSenderFromReplies',['../classtd_1_1td__api_1_1block_message_sender_from_replies.html',1,'td::td_api']]],
  ['botcommand_2483',['botCommand',['../classtd_1_1td__api_1_1bot_command.html',1,'td::td_api']]],
  ['botinfo_2484',['botInfo',['../classtd_1_1td__api_1_1bot_info.html',1,'td::td_api']]]
];
